version: '3'

services:
  wp:
    image: wordpress:latest
    volumes:
      - ./config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.wpsviluppo-plugin.rule=Host(`wp-${DOMAIN}`)
      - traefik.http.routers.wpsviluppo-plugin.tls=true
      - traefik.http.routers.wpsviluppo-plugin.tls.certresolver=cloudflare
      - traefik.http.routers.wpsviluppo-plugin.entrypoints=websecure

  pma:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
    volumes:
      - ./config/pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./config/pma_config.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.pmasviluppo-plugin.rule=Host(`pma-${DOMAIN}`)
      - traefik.http.routers.pmasviluppo-plugin.tls=true
      - traefik.http.routers.pmasviluppo-plugin.tls.certresolver=cloudflare
      - traefik.http.routers.pmasviluppo-plugin.entrypoints=websecure

  db:
    image: mysql:latest
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.dbsviluppo-plugin.rule=Host(`db-${DOMAIN}`)
      - traefik.http.routers.dbsviluppo-plugin.tls=true
      - traefik.http.routers.dbsviluppo-plugin.tls.certresolver=cloudflare
      - traefik.http.routers.dbsviluppo-plugin.entrypoints=websecure

volumes:
  db_data:

networks:
  frontend:
    external: true
